version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 10.120.14.101
      #KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    restart: always
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.0
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.0
    container_name: kibana
    restart: always
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  mysql:
    image: mysql:5.7.25
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_db:/tmp/mysql
      - ./mysql_code/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_running_helper
      MYSQL_USER: srh
      MYSQL_PASSWORD: srh
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  redis:
    image: redislabs/rejson:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  jupyter:
    image: karaswinds/team_project_python
    container_name: jupyter
    restart: always
    ports:
      - "8888:8888"
      - "80:5000"
    volumes:
      - ./py_code:/home/jovyan/work
    command: "start-notebook.sh --NotebookApp.token=''"
  ngrok:
    depends_on:
      - jupyter
    image: wernight/ngrok
    container_name : ngrok
    restart: always
    ports:
      - '4040:4040'
    environment:
      NGROK_PORT: jupyter:5000
      NGROK_REGION: ap
  admin:
    image: adminer
    container_name: admin
    restart: always
    restart: always
    ports:
      - "8080:8080"
